const express = require('express');
const app = express();
const cors = require('cors');

app.use(cors());

const CC_Items = [
    { title: 'Cloud Computing Syllabus', url: '../CC/1.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Introduction', url: '../CC/2.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Advantages and Disadvantages of Cloud Computing', url: '../CC/3.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'History of Cloud Computing', url: '../CC/4.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Architecture', url: '../CC/5.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Technologies', url: '../CC/6.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Vs Grid Computing', url: '../CC/7.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'How does Cloud Computing Work', url: '../CC/8.html', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Applications', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Security Risks of Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Architecture', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Features', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS  Pros&amp;Cons', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Application', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Console Mobile App', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Account', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Management Console', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Developer Tools', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Management Tools', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Live Class Video', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Analytics', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS S3', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Hybrid Cloud', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Community Cloud', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Service Models', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Workspace', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Lambda', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Storage', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Direct Connect', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS CloudFront', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Types of Cloud', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Public Cloud', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Private Cloud', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS RDs', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Database', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Autoscaling', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Live Class Video - 2', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Live Class Video - 3', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Live Class Video - 4', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud AWS Account Creation', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Infrastructure as a Service - (IaaS) :', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Platform as a Service - PaaS', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Software as a Service - SaaS', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Virtualization in Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Data Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Glacier', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Hardware Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Snowball', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Software Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Aurora', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Route', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS ElastiCache', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS DynamoDB', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Kinesis', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Redshift', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Cloudsearch', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS CloudFormation', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'How AWS Cloudtrail Works', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS EMR', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS SNS', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'What is AWS SQS', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS SES', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS SDK', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'What is AWS MFA', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Server Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Storage Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'OS Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Linux OS Virutualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Windows OS Virutualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Service Provider Companies', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'How to create Amazon EC2 Window Instances', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Vs Azure Vs Google Cloud Platform', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Elastic Beanstalk', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS EBS', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS ELB', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Best AWS EC2', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS VPC', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS SWF', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS IAM', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Infrastructure', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Operating System Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Management', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Hardware and Software Virtualization', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Identity as a Service', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing for Business', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Cube Model', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Mobile Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Future of Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Big Data VS Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing - Basic Electronics', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing - Electronics Sensor', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing - Signals in Electronics', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'What is AWS KMS', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS WorkMail', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Data Pipeline', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'What is Amazon Machine Learning', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS IoT', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS LightSail', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Pricing Benefits', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Video 1', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Video 2', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Video 3', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Video 4', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Video 5', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Introduction Video', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Rest API', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Services', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'AWS Services Cont..', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Advanced Sessions', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Cloud Computing Interview Questions', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'What is Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Service Models in Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Types of Cloud Computing', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' },
    { title: 'Differences Between Scalability and Elasticity', url: '#', icon: 'https://www.kaashiv.com/img/checked.png' }

];

app.get('/CC', (req, res) => {
  res.json(CC_Items);
});

app.listen(3000, () => console.log('API running on http://localhost:3000'));










